feeds = [
    {"feed_url": "https://www.bleepingcomputer.com/feed/", "feed_source": "BleepingComputer"},
    {"feed_url": "https://thehackernews.com/rss.xml", "feed_source": "The Hacker News"},
    {"feed_url": "https://cybersecuritynews.com/feed/", "feed_source": "CybersecurityNews"},
    {"feed_url": "https://krebsonsecurity.com/feed/", "feed_source": "Krebs on Security"},
    {"feed_url": "https://cve.mitre.org/data/rss/allitems.xml", "feed_source": "MITRE CVE"},
    {"feed_url": "https://feeds.feedburner.com/securityweek", "feed_source": "SecurityWeek"},
    {"feed_url": "https://us-cert.cisa.gov/ncas/alerts.xml", "feed_source": "US-CERT National Cyber Awareness System"},
    {"feed_url": "https://isc.sans.edu/rssfeed.xml", "feed_source": "SANS Internet Storm Center"},
    {"feed_url": "https://www.zerodayinitiative.com/feed.xml", "feed_source": "Zero Day Initiative (ZDI)"},
    {"feed_url": "https://threatpost.com/feed/", "feed_source": "Threatpost"},
    {"feed_url": "https://www.darkreading.com/rss_simple.asp", "feed_source": "Dark Reading"},
    {"feed_url": "https://www.databreachtoday.com/rssFeeds.php", "feed_source": "DataBreachToday"},
    {"feed_url": "https://cvefeed.io/rssfeed.xml", "feed_source": "CVEFeed"},
    {"feed_url": "https://www.exploit-db.com/rss.xml", "feed_source": "Exploit-DB"},
    {"feed_url": "https://unit42.paloaltonetworks.com/feed/", "feed_source": "Unit 42 (Palo Alto)"},
    {"feed_url": "https://research.checkpoint.com/feed/", "feed_source": "Check Point Research"},
    {"feed_url": "https://securelist.com/feed/", "feed_source": "Kaspersky SecureList"},
    {"feed_url": "https://www.crowdstrike.com/blog/feed/", "feed_source": "CrowdStrike"},
]
